[workspace]
resolver = "2"


members = [
    "voxelcraft_client",
    "voxelcraft_server",
    "voxelcraft_mod",
    "mods/test",
    "packs/test",
    "core",
    "libs/block_chunk",
    "libs/wgpu_async_utils",
    "libs/face_texture_map",
    "libs/camera"
]